services:
  tei_embedding:
    image: ghcr.io/huggingface/text-embeddings-inference:cuda-1.9
    container_name: tei_dense_embedding
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all          # or change to 1, or list device_ids
              capabilities: [ gpu ]
              options:
                runtime: nvidia
    ports:
      - "${TEI_DENSE_EMBEDDING_PORT:-8100}:80"
    volumes:
      - tei-cache:/data
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HF_TOKEN=${HF_TOKEN:-}
    command: >
      --model-id ${DENSE_MODEL_NAME:-Qwen/Qwen3-Embedding-0.6B}
      --api-key ${SERVING_API_KEY:-token}
      --dtype ${TEI_DTYPE:-float16}
      --max-batch-tokens ${TEI_MAX_BATCH_TOKENS:-16384}
      --max-concurrent-requests ${TEI_MAX_CONCURRENT_REQUESTS:-512}
      --payload-limit ${TEI_PAYLOAD_LIMIT:-2000000}
volumes:
  tei-cache: